### PR TITLE
Added support for xcode 8.x

### LINKED ISSUE #41: Please make this compatible with Xcode 8
Getting this error

```
Amaro requires the default Xcode command line tools to point to Xcode 7.0 or later. Yours point to 8.0.
Install Xcode 7.0 or later, and run "xcode-select" to point to that.
```

### PR DESCRIPTION
**Pull request by karnikad**
Modified the code to make it work with xcode 8.x. Had to make the
following changes:
1. Changed the xcode version check to now allow Xcode 8.x
2. Added --allow-unrelated-histories flag to git as git 2.11 is shipped
with mac os x sierra and the previous command was failing here.

Fixes #41 and #42

### CODE REVIEW

**Comment by karnikad** [comment]
@misterfifths can you please help me with this PR. Seems like the tests have timed out. I don't know whether it is due to the TravisCI configuration. They have now xcode 7.3.1 images from November 2016.

**Comment by misterfifths** [comment]
Hey! This looks great! Sorry for the delay.. it's been a crazy week. I'll take a look at the Travis situation tomorrow. Thanks for your work!

**Comment by misterfifths** [comment]
Hm.. well, not the most scientific approach, but I did a few things and got it working:

- Switched to the `xcode8.1` image for Travis
- Switched from `xctool` back to `xcodebuild`. `xctool`'s build functionality is apparently deprecated.
- Updated xcconfigs and Cocoapods integration

The branch is here: https://github.com/crushlovely/Amaro/tree/karnikad-master. Probably what makes sense is for you to merge that into your fork, which will update this PR. From your clone of your fork, something like this:

```sh
$ git remote add upstream https://github.com/crushlovely/Amaro.git
$ git fetch upstream
$ git merge upstream/karnikad-master
# make sure everything is to your liking for the PR, and then:
$ git push
```

Thanks again!

**Comment by misterfifths** [comment]
:+1: Looks good to me! All merged.

**Comment by karnikad** [comment]
Thank you for the merge.

**Pull request merged**
